language: rust
sudo: false

cache: cargo
rust:
  - stable
  - beta
  - nightly

after_success:
  - curl https://stainless-steel.github.io/travis/documentation.sh | bash

env:
  global:
    - secure: A0y29X6C59DrauybvT0ZK5dV0QpfneK0vo0ZbsfpA+Mdf7yb2QFpk/ed1W6P9JZP6cRoRTMZrlcmCR8NzOHFzIBFouBj7EN40DALU2CuI8gjl5xkoXIrqHHW4lGfHu+40MSGMgCGk4xVhm5rYM5DDMYrZJKyLr8U4QCM24XkMED/+1PIqq4lcWx3FVQfcBUNxjsJBpFlb/1GQA1DHva5f+w6XZUqN9A8jKjFRqS8BxTPmwsL2ILNbqpJjdUowMKUeCDdn7pWDUi6WdgCoEOW9GVo5u6/6lBFTVzy2zPyrqr4s5QrR413zMcsjP8XVHrIsGSmUKAuj4rNQ5yNVxcSvqkEmESyg1TBJe2HgHKneOeSwsMwC/rOP739PXJ5MRBmip3viVgGSng2ellni7zvn9QhG8uiu0NCbgtw3Gmc6pWk23WWV5gZ4q5Ny6iTvEQwOYRR25QN0zX5VhNP2Hg11/1UtqdokOSYuaM4bt/HDBpO5zC7Vbsc/3xN2XY2+x/FKAVPdsMtsvFXDh/sXa2JUAcGNUeA1abI47xC6+HPcooq4WdHkt1mIALARMS7jCkHTs2q/nSOkCs78zyfN2vTtH1IMqnJiH1EvGxebmdzLe+Vx2h4q9qSoZNjKBZv70oO1tegFluplnhrjGPkSXuAlhRgUp8yYtiJh0VnBKvCAes=

notifications:
  email: false
