language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    - RUSTDOC_VERSION=nightly
    - secure: WztLjhfri7OH1XrL6qkdOvkA+Ux/IQFFtwmbweXvB3Zu3/uFh7/R8khELk6oBCOU3PMLq7hjWXHLg6d1JGoPZDJydey2UaN38sB64ahrmfMP74JMuqxcbWGPsw/8ufI0NinVuakeQAnJMrl1E9re8uVTK7x77u1urNxOwtzb3vdZe2v1WH4UpPycn6xNp5OnQNb4GaCc7vXKUWdhQvav5ZYG3i92Bb9Tf9fFgnZheAioN9cL9ZVabv4EKxdBoJvgmN/z+QqFSB++RDQ2dc6JCS9i3xiNTRXrHdBU34c61uOwdX9uKzbm2sOkmB4SQScge82TXGMEkZaitUJYAE/KnnFUeKzcGD+Y+B2/kXy2hn06aBEyaKmtNXrUyc+JKpmM2I89oFVVyzT03OUoi8GFP9EHctPxZAktAucVgQrIlogL/2eCCO2yy3lVeDU61nfzsCNeGfslRmsB8mJyPwpeiBUHbk27NsZxzsYXWGKcdNQJ6vp8F2OqHnnDphBtBY559/eOqXbpXSd1YvqggCoMVnN2L4LwY0mHcValAbUWgc48cjXFqlbk2bgL8WAvB7pKM/ImHM0xvRXoCoQhIUw09F+3Kft3dmddDmrmgY0vGxYKt4oNDHT864FpeGMjmqLb/QxxXLlv/ebPmtDwLOKg0WywaZyOZ+7G1BcDKWv6a0g=

notifications:
  email: false
